[versions]
junit = "4.13.2"
slf4j = "1.7.36"
xmlwriter = "1.0.4"

[libraries]
annotations = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version = "2.4.100" }
berlioz = { module = "org.pageseeder.berlioz:pso-berlioz", version = "0.11.6" }
cache-api = { module = "javax.cache:cache-api", version= "1.0.0" }
ecache = { module = "net.sf.ehcache:ehcache", version = "2.8.8" }
jakarta-xml-bind = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version = "2.3.3" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
junit = { module = "junit:junit", version.ref = "junit"}
servlet-api = { module = "javax.servlet:javax.servlet-api", version = "3.1.0" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
xmlwriter = { module = "org.pageseeder.xmlwriter:pso-xmlwriter", version.ref = "xmlwriter" }

[plugins]
jreleaser = { id = "org.jreleaser", version = "1.18.0" }
